name: Daily AI Analysis

on:
  schedule:
    - cron: '1 4 * * *'  # 每天台灣晚上10點 (UTC+8 = UTC 1AM)
  workflow_dispatch:     # 可手動執行

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install

    - name: Create .env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
        echo "TELEGRAM_USER_ID=${{ secrets.TELEGRAM_USER_ID }}" >> .env

    - name: Run analysis
      run: |
        mkdir -p outputs
        poetry run python src/main.py --ticker AAPL,TSLA,NVDA --show-reasoning > outputs/report.txt

    - name: Send Telegram Notification
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
        -d chat_id="${{ secrets.TELEGRAM_USER_ID }}" \
        -d text="$(cat outputs/report.txt | head -c 4000)"
